package xiaozhi.modules.agent.dto;

import java.io.Serializable;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

/**
 * Agent creation DTO
 * For creating agents; id, agentCode, and sort are generated by the system.
 */
@Data
@Schema(description = "Agent creation payload")
public class AgentCreateDTO implements Serializable {
    private static final long serialVersionUID = 1L;

    @Schema(description = "Agent name", example = "Customer Support Assistant")
    @NotBlank(message = "Agent name is required")
    private String agentName;
}